name: "Build CI"

on:
  workflow_dispatch:
    inputs:
      publish_artifacts:
        description: "Publish Docker image regardless of branch"
        type: boolean
        default: false
        required: true
  merge_group:
  pull_request:
  push:
    branches:
      - master

jobs:
  maven-build:
    uses: ./.github/workflows/mvn_build.yaml
    secrets: inherit

  docker-build:
    needs: maven-build
    uses: ./.github/workflows/docker_build.yaml
    with:
      push: ${{ github.event.inputs.publish_artifacts }}
    secrets: inherit
