name: "Build CI"

on:
  workflow_dispatch:
    inputs:
      publish_artifacts:
        description: "Publish Docker image regardless of branch"
        type: boolean
        default: false
  merge_group:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu
    env: 
      PUBLISH_ARTIFACT: ${{ github.event.inputs.publish_artifacts }}
    steps:
      - name: print
        run: echo "${{ env.PUBLISH_ARTIFACT }}"
      
  maven-build:
    uses: ./.github/workflows/mvn_build.yaml
    secrets: inherit

  docker-build:
    needs: maven-build
    uses: ./.github/workflows/docker_build.yaml
    with:
      push: ${{ fromJson(github.event.inputs.publish_artifacts) }}
    secrets: inherit
