name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  docker-push:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'
        
    - name: Build with Maven
      run: mvn -B package
      
    - name: Copy Jar to build
      run: cp target/*.jar build/command-api.jar

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
        
    - name: Build the Version Docker image
      run: docker build -t tag365/tm-streams-support-api:${{ env.RELEASE_VERSION }} \build
    
    - name: Build the Latest Docker image
      run: docker build -t tag365/tm-streams-support-api:latest \build
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker release image
      run: docker push tag365/tm-streams-support-api:${{ env.RELEASE_VERSION }}
    
    - name: Push Docker latest image
      run: docker push tag365/tm-streams-support-api:latest
      
