name: Docker

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Download Jar
        uses: actions/download-artifact@v3
        with:
          name: command-api
          path: build/command-api.jar
          
      - name: debug
        shell: bash
        run: |
          cd build
          file command-api.jar
          ls -l
        
      - name: debug
        shell: bash
        run: |
          cd build
          ls -l

      - name: Extract Project version
        run: |
          echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Add snapshot
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          echo ${{ env.RELEASE_VERSION }}
          echo "RELEASE_VERSION=${{ env.RELEASE_VERSION }}-SNAPSHOT" >> $GITHUB_ENV
    
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: ./build
          push: ${{ inputs.push }}
          tags: tag365/tm-streams-support-api:${{ env.RELEASE_VERSION }} , tag365/tm-streams-support-api:latest
